angular.module('simuladorApp', ['ui.router', 'ui.bootstrap', 'angular-growl'])
    .config(['growlProvider', function (growlProvider) {
        growlProvider.globalTimeToLive(2000);
    }])
    .factory("usuarioService", usuarioService)
    .factory("equipoService", equipoService)
    .factory("resultadoService", resultadoService)
    .factory("partidoService", partidoService)
    .controller('LoginController', LoginController)
    .controller('RegisterController', RegisterController)
    .controller('UsuarioController', UsuarioController)
    .controller('EquipoController', EquipoController)
    .controller('ResultadosController', ResultadosController)
    .controller('PartidoController', PartidoController)
    .config(routes)